services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    hostname: tailscaled
    environment:
      - TS_AUTHKEY=${TS_AUTH_KEY}
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - ./tailscale_data:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
  proxy-server:
      image: nginx
      network_mode: service:tailscale
      depends_on: 
        - tailscale
