- name: Disable ufw 
  ansible.builtin.command:
    cmd: ufw disable

- name: Disable ssh Password Authentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#PasswordAuthentication "
    line: "PasswordAuthentication no"
    validate: 'sshd -t -f %s' 
  notify: restart_sshd

- name: Disable root SSH login
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?PermitRootLogin"   
    line: 'PermitRootLogin no'
    state: present
    validate: 'sshd -t -f %s'      # validates config before saving
  notify: restart_sshd



